#!/bin/bash
benchmark='
{
	"DaggerHashimoto": 10000,
	"x16r": 115,
	"Beam": 155
}'

nh_algos="
'Scrypt' : 0,
'SHA256' : 1,
'ScryptNf' : 2,
'X11' : 3,
'X13' : 4,
'Keccak' : 5,
'X15' : 6,
'Nist5' : 7,
'NeoScrypt' : 8,
'Lyra2RE' : 9,
'WhirlpoolX' : 10,
'Qubit' : 11,
'Quark' : 12,
'Axiom' : 13,
'Lyra2REv2' : 14,
'ScryptJaneNf16' : 15,
'Blake256r8' : 16,
'Blake256r14' : 17,
'Blake256r8vnl' : 18,
'Hodl' : 19,
'DaggerHashimoto' : 20,
'Decred' : 21,
'CryptoNight' : 22,
'Lbry' : 23,
'Equihash' : 24,
'Pascal' : 25,
'X11Gost' : 26,
'Sia' : 27,
'Blake2s' : 28,
'Skunk' : 29,
'CryptoNightV7' : 30,
'CryptoNightHeavy' : 31,
'Lyra2Z' : 32,
'X16R' : 33,
'CryptoNightV8' : 34,
'SHA256AsicBoost' : 35,
'Zhash' : 36,
'Beam' : 37,
'GrinCuckaroo29' : 38,
'GrinCuckatoo31' : 39,
'Lyra2REv3' : 40,
'MTP' : 41,
'CryptoNightR' : 42,
'CuckooCycle' : 43,
"

echo "$(date -R) Autoswitch for NiceHash started"
echo $benchmark | jq '.'
echo $nh_algos | jq '.'
for (( i=0; i < ${#benchmark[@]}; i++ )); do
	algo=$benchmark[$i]
	echo $nh_algos | jq ".$algo"
done